### PR TITLE
Gradle versioning

### PR DESCRIPTION
**Pull request by duskox**
Suggestion on how to name apk's maybe?

### CODE REVIEW

**Comment by peter-tackage** [comment]
@duskox Release build is now working, review will happen shortly.

**Comment by peter-tackage** [comment]
@duskox The release build is failing in this branch. You will need to rebase to get the latest changes which fix that.

**Comment by peter-tackage** [comment]
@duskox This rebasing seem wrong, I'm reasonably certain you haven't modified 160+ files in this PR :-)

**Comment by duskox** [comment]
@peter-tackage true, not sure why it happened, will look at it later (not 5 months later) :)

**Pull request closed without merging**
