### PR TITLE
Testing Sound parcel

### PR DESCRIPTION
**Pull request by tomaszpolanski**

### CODE REVIEW

**Comment by peter-tackage** [comment]
Thanks @tomaszpolanski I'll check this out (and read the blog) soon.

**Comment by tomaszpolanski** [comment]
Don't review it yet, found a better solution for it

**Comment by tomaszpolanski** [comment]
I've improved it

**Comment by peter-tackage** [comment]
@tomaszpolanski Approved, but Travis is rejecting the build requests due to them being flagged as potential abuse (!) (https://travis-ci.org/futurice/freesound-android/requests). I've written to Travis support to sort it out.

**Pull request merged**
