### PR TITLE
Use Sonar plugin 2.6-rc1

### PR DESCRIPTION
**Pull request by peter-tackage**

### CODE REVIEW

**Comment by joan-domingo** [comment]
Can I see the sonarqube report? @peter-tackage can you share the link? or do I need to create an account?

**Comment by peter-tackage** [comment]
The reports should go here: https://sonarcloud.io/dashboard?id=freesound-android but I'm not sure it's working again yet.

**Comment by joan-domingo** [comment]
We are adding the plugin but it isn't working. What needs to be done yet?

**Comment by peter-tackage** [comment]
Actually I think it *is* working, but in Travis, it only runs on master branch. So we can't see the results here.

**Comment by peter-tackage** [comment]
Hmm, it seemed the emulator was just timing out. @joan-domingo perhaps we merge this so we can see the results in SonarQube?

**Comment by joan-domingo** [comment]
I approved this PR before your message :P

**Pull request merged**
